
version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1

jobs:  
  executor-CF:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
         aws-access-key-id: AWS_ACCESS_KEY_ID
         aws-region: AWS_DEFAULT_REGION
         aws-secret-access-key: AWS_SECRET_ACCESS_KEY
      - run:
         name: deploy cloudformation
         command: 
          set -x
          aws cloudformation deploy --stack-name task13 --template-file ~/environment/TEST/TEST-CI/cloudformation/NW.yaml
          
workflows:
  TEST-CI:
    jobs: 
     - executor-CF

