# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.4

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:  
  executor-CF:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
         aws-access-key-id: AWS_ACCESS_KEY_ID
         aws-region: AWS_DEFAULT_REGION
         aws-secret-access-key: AWS_SECRET_ACCESS_KEY
      - run:
         name: deploy-CF
         command: 
          set -x
          aws cloudformation deploy --stackname test --template-fale cloudformation/NW.yml
          
workflows:
  task15:
    jobs: executor-CF

