
version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.4
  ansible-playbook: orbss/ansible-playbook@0.0.5
  python: circleci/python@2.0.3

jobs:
  cfn-lint:
    executor: python/default
    steps:
      - checkout
      - run: pip install cfn-lint
      - run:
          name: run cfn-lint
          command: |
            cfn-lint -i W3002 -t cloudformation/*.yaml
  executor-CF:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
         aws-access-key-id: AWS_ACCESS_KEY_ID
         aws-region: AWS_DEFAULT_REGION
         aws-secret-access-key: AWS_SECRET_ACCESS_KEY
      - run:
         name: deploy cloudformation
         command: 
          set -x

          aws cloudformation deploy --stack-name task13 --template-file cloudformation/NW.yaml

  executor-Ansible:
    executor: ansible-playbook/default
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "d9:97:25:47:37:f2:0f:67:36:0d:e3:fb:b5:71:17:42"
      - ansible-playbook/install:
          version: 2.9.27
      - run: scp -oStrictHostKeyChecking=no
      - ansible-playbook/playbook:
          playbook: ansible/playbook.yml
          playbook-options: "-u ec2-user -i ansible/inventory --private-key .ssh/RAISE-KEY.pem"
workflows:
  RAISE-13:
    jobs: 
     - cfn-lint
     - executor-CF
     - executor-Ansible:
         requires:
           - "executor-CF"

